name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Android SDK Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p "$HOME/android-sdk"
          cd "$HOME/android-sdk"
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools
          mv cmdline-tools cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_HOME" "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build APK with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: .  # Directory containing main.py and buildozer.spec

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: ./bin/*.apk
